export const LogType = {
  USER_ACTIVITY: 'USER_ACTIVITY',
  CLICK_ACTIVITY: 'CLICK_ACTIVITY',
  TRANSITS_ACTIVITY: 'TRANSITS_ACTIVITY',
  PAYOUT_ACTIVITY: 'PAYOUT_ACTIVITY',
  ORDER_ACTIVITY: 'ORDER_ACTIVITY',
  SMALLCASE_ACTIVITY: 'SMALLCASE_ACTIVITY',
};

export const TransitionsType = {
  REFERRAL: 'REFERRAL',
  COMMOTION: 'COMMOTION',
  OTHERS: 'OTHERS',
};
